services:
#   app:
#     image: laravel:latest
#     container_name: laravel_app
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html
#       - ./vendor:/var/www/html/vendor
#       - ./node_modules:/var/www/html/node_modules
#     networks:
#       - laravel_network
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=${MYSQL_DATABASE}
#       - DB_USERNAME=${MYSQL_USER}
#       - DB_PASSWORD=${MYSQL_PASSWORD}
#     depends_on:
#       - db
#     ports:
#       - "8000:8000"
#     command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: laravel_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
    environment:
      MYSQL_DATABASE: silveira
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
